### ISSUE TITLE
Breaks Outliner plugin functionality

### ISSUE THREAD

**Issue by lilruffian** [hipstersmoothie/obsidian-plugin-prettier#5]
Hey not sure if anyone has flagged this with you, but I think that this plugin is responsible for breaking functionality in the [Obsidian Outliner](https://github.com/vslinko/obsidian-outliner) plugin. When both plugins are enabled, Outliner doesn't seem to recognize lists correctly until Prettier is run on the file. If prettier is disabled entirely, Outliner works fine. 

cc @vslinko

**Comment by vslinko** [comment]
@brandonxoliver Could you please provide an example file where everything breaks?

**Comment by lilruffian** [comment]
Seems to be working fine now. Must be my error. Sorry! Closing this.
