### ISSUE TITLE
It doesn't work on obsidian v0.13.14

### ISSUE THREAD

**Issue by younho9** [hipstersmoothie/obsidian-plugin-prettier#9]
I've been using this plugin since obsidian v0.12.19, but this plugin does not work since I recently updated it to version obsidian v0.13.14

**Comment by meskill** [comment]
Actually, the problem is with new `Live Preview` mode introduced in the latest obsidian versions

**Comment by chrisgrieser** [comment]
can also confirm, does not work anymore with newer version of Obsidian.

**Comment by n-a-m-e** [comment]
Quick fix until this is updated is to edit .obsidian/plugins/obsidian-plugin-prettier/main.js and replace
```ct=Le.getOption("tabSize")||4,lt=Le.getOption("indentWithTabs")??!0```
with
```ct=4,lt=false```

**Comment by BindingOx** [comment]
> Quick fix until this is updated is to edit .obsidian/plugins/obsidian-plugin-prettier/main.js and replace `ct=Le.getOption("tabSize")||4,lt=Le.getOption("indentWithTabs")??!0` with `ct=4,lt=false`

do you know how to make it work with latest? I dont see the text to edit in that file

edit: ok nvm, a reinstall of the plugin showed it
